title: Statslabs -- Statistical Computing with C++
email: ypan1988@gmail.com
description: The statslabs.github.io website

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: statslabs
github_username:  statslabs

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - about.md
  - docs/matrix/index.md


# Collections settings
collections:
  documentation:
    output: true
    permalink: /:collection/:path
# End
#
